### ISSUE TITLE
Formal docker container for FVS?

### ISSUE THREAD

**Issue by jgrn307** [USDAForestService/ForestVegetationSimulator#30]
Hi all!  We've been using a dockerized container we built for FVS for a few years now -- I was wondering if there is an official container for FVS at this point or, if not, if there is any interest in us providing our DOCKERFILE or repo to the community?  We are using this container within the Google Cloud Platform as well as other HPC environments.  Cheers!

**Comment by wagnerds** [comment]
Greetings, We currently don't have an official Docker container for FVS.  You are welcome to submit a pull request and we will be happy to review it.  Thanks!
