### ISSUE TITLE
Retrieving process data & Error code guidelines?

### ISSUE THREAD

**Issue by zyliu2020** [USDAForestService/ForestVegetationSimulator#34]
Hi there,

I am an academic user of the Open-FVS (20230106 version) from the operations research community. I have been running simulations with the FVSca variant on MacOS via APIs from Python and wonder whether you could help with two questions:

1. Currently when I run FVS with TREEDATA for multiple cycles (say from 2018 to 2068 with a cycle length of 10 years), for each result (simulation result for 2028, 2038, 2048, 2058, 2068), I only get a summary data of the number of trees, DBH, cubic feet, etc. for the whole forest stand. May I ask whether there is any way to retrieve additional intermediate simulation data so that I can use results from say 2038 to construct a new TREEDATA set that captures richer information about the stand which could allow me to feed into a new round of simulation starting from 2038 so as to explore alternative forest management options?
2. When using FVS to run simulations, I sometimes receive an error code saying "Process finished with exit code 0" or "Process finished with exit code 1". Do you have an exit code book/guidelines so that I may understand what has gone wrong in my script?

Thanks so much for your kind help!

Best,
Ann

**Comment by wagnerds** [comment]
Greetings, you may what to visit our website (https://www.fs.usda.gov/fvs/) and review the documentation for the Essential FVS Guide<https://www.fs.usda.gov/fmsc/ftp/fvs/docs/gtr/EssentialFVS.pdf> and the Keyword Guide<https://www.fs.usda.gov/fmsc/ftp/fvs/docs/gtr/keyword.pdf>.  If you have the ability to run a VM on your machine, I would also advise downloading and installing FVS and using our interface and training materials provided in the download and from our website to become familiar with what types of products FVS is capable of producing.  Pay special attention to the CYCLEAT, TREELIST, and TREEDATA keyword.  Hopefully, you API you are using is capable of leveraging some of these Keywords.  If you need further assistance, please contact our helpdesk email address at Greetings, you may what to visit our website (https://www.fs.usda.gov/fvs/) and review the documentation for the [Essential FVS Guide](https://www.fs.usda.gov/fmsc/ftp/fvs/docs/gtr/EssentialFVS.pdf) and the [Keyword Guide](https://www.fs.usda.gov/fmsc/ftp/fvs/docs/gtr/keyword.pdf).  If you have the ability to run a VM on your machine, I would also advise downloading and installing FVS and using our interface and training materials provided in the download and from our website to become familiar with what types of products FVS is capable of producing.  Pay special attention to the CYCLEAT, TREELIST, and TREEDATA keyword.  Hopefully, you API you are using is capable of leveraging some of these Keywords.  If you need further assistance, please contact our helpdesk email address at [sm.fs.fvs-support@usda.gov](mailto:sm.fs.fvs-support@usda.gov)

**Comment by zyliu2020** [comment]
Hi there,

I and my collaborator have read thoroughly the two documents you mentioned above. However, we did not see anything addressing these two issues. According to this [archived page](https://sourceforge.net/p/open-fvs/wiki/StopRestart/) for OpenFVS, the only way to access the stop/restart function from FVS is via the command line. However, that page only provided very limited information. Could you share more detailed guidelines for the stop/restart function?

For the error code, I did not see anything mentioned in the documentation at all. I suspect maybe that is because the guidelines do not include any instruction for command line access to FVS (they focus on the GUI instead). Could you point me to debugging advice when using FVS via command lines?

Best,
Zhuoyang

**Comment by DavidLRfs** [comment]
I have only used the stop/restart option in the Windows command line. And Yes, only works in a command line environment, or possibly through API but i have not done that, not the interface. Bottom line though is that if you are not absolutely familiar the FVS internal processes and data structures, you are wasting your time with these options. For that reason the information available is limited.
https://github.com/USDAForestService/ForestVegetationSimulator/wiki#using-fvs

"Error code": Stop (exit) codes -Essential FVS, 9.1 FVS Error and Warning Messages. Look for "Severity =" Those severity codes relate directly to the Stop code FVS displays at end of run.

**Comment by wagnerds** [comment]
There is also a bit of information on what stop codes are available in the API information: https://github.com/USDAForestService/ForestVegetationSimulator/wiki/FVS-API#stop-points
