### ISSUE TITLE
Not installing on macOs 12.4

### ISSUE THREAD

**Issue by geoffroyO** [USDAForestService/ForestVegetationSimulator#4]
Hi, I tried to install FVS in command line on macOs using the wiki, but it looks like it isn't working I get the following error, when I try to compile FVS:

First for the command $cmake -G"Unix Makefiles" . , there is a dev warning: 

CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   FVS_bc
   FVSfofem
   FVSsql

To compile the variant using make I then get this error:

ForestVegetationSimulator/dbsqlite/fvsqlite3.c:244:12: error: '__declspec' attributes are not enabled; use '-fdeclspec' or '-fms-extensions' to enable support for __declspec attributes
    extern __declspec(dllexport) int fsql3_reset_  // GCC compiler, Windows OS

It looks like it doesn't find on which OS I am despite the previous Cmake.

Finally I would like to know if there is any docker image on which FVS works ? 

Thanks !

**Comment by DavidLRfs** [comment]
Good afternoon Geof,
The FVS staff has no Mac PCs to check or test anything. We only have Windows 10 PCs. I would suggest you reach out to the Mac community for some leads on a Windows emulator that may work. Perhaps there may be some useful information available on [StackOverflow](https://stackoverflow.com/) as well.
       -Lance
