### ISSUE TITLE
FVS units database?

### ISSUE THREAD

**Issue by jgrn307** [USDAForestService/ForestVegetationSimulator#48]
Is there a table someplace that contains a full listing of the output names and their units in a "readable" fashion (not the PDF)?  I'd like to be able to do dynamic unit conversion using e.g. python without having to first hand-make a csv.  Ideally, this would follow some standards like e.g. python's "pint" units: 

https://pint.readthedocs.io/en/stable/getting/index.html

Something like:
FVS_Carbon:Standing_Dead = "ureg.ton / ureg.acre" (this is how pint would define it)

If this doesn't currently exist, would you consider making a csv-based "registry" of all table:columns combinations with their description, data_type, units, etc instead of only having the PDF?

**Comment by wagnerds** [comment]
[DBSUserGuide.docx](https://github.com/user-attachments/files/18028005/DBSUserGuide.docx)
There is a table at the back of the DBS Users Guide that may be useful.  A Word version has been attached.

You might also be able to make use of the files in the `metric` directory, though I would be careful with those subroutines as they may not be as well maintained as the standard subroutines.
